on:
  pull_request:
    branches:
      - update-*

jobs:
  regenerate_sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: |
          sudo apt update
          sudo apt install -y python3-yaml
      - run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "Workflow trigger"
      - run: |
          ./regenerate-sources.sh
      - run: |
          git push
